Loaders

In [1]:
from sklearn.datasets import load_iris
data = load_iris()

In [4]:
type(data)

sklearn.utils.Bunch

Contains i) data ii) target iii) feature_names iv)target_names v)DESCR vi) filename

In [8]:
data.data.shape

(150, 4)

In [10]:
data.target.shape

(150,)

In [11]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [13]:
data.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [14]:
data.filename

'iris.csv'

In [16]:
type(data.data)

numpy.ndarray

In [26]:
data.data[:5]  # number of rows

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [44]:
data.data[:,0]  # selecting 0 column

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [52]:
data.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [53]:
feature_matrix,label_vector = load_iris(return_X_y= True)

In [55]:
feature_matrix.shape

(150, 4)

# Loading diabetes data set

In [56]:
from sklearn.datasets import load_diabetes

In [60]:
data = load_diabetes(return_X_y= True, as_frame=True)

In [62]:
type(data)

tuple

In [64]:
feature_matrix,label_vector = data

In [65]:
feature_matrix

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019908 -0.017646  
1   -0.039493 -0.068330 -0.092204  
2   -0.002592  0.002864 -0.025930  
3    0.034309  0.022692 -0.009362  
4   -0.002592 -0.031991 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018118  0.044485  
439 -0.011080 -0.046879  0.015491  
440  0.026560  0.044528 -0.025930  
441 -0.039493 -0.004220  0.003064  

[442 rows x 10 columns]

In [66]:
label_vector

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [68]:
feature_matrix.dtypes

age    float64
sex    float64
bmi    float64
bp     float64
s1     float64
s2     float64
s3     float64
s4     float64
s5     float64
s6     float64
dtype: object

In [69]:
label_vector.dtypes

dtype('float64')

# Fetchers

In [70]:
from sklearn.datasets import fetch_california_housing

In [71]:
data = fetch_california_housing()

In [74]:
data.target_names

['MedHouseVal']

In [75]:
data.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [76]:
import pandas as pd

In [80]:
feature_matrix= pd.DataFrame(data=data.data,columns=data.feature_names)

In [81]:
feature_matrix

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [82]:
data.data.shape

(20640, 8)

In [90]:
data.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [91]:
label_vector = pd.DataFrame(data = data.target,columns = data.target_names)

In [92]:
label_vector

MedHouseVal
0            4.526
1            3.585
2            3.521
3            3.413
4            3.422
...            ...
20635        0.781
20636        0.771
20637        0.923
20638        0.847
20639        0.894

[20640 rows x 1 columns]

# Generators

In [95]:
from sklearn.datasets import make_regression
?make_regression

In [109]:
feature_matrix,label_vector = make_regression(n_samples=100,n_features =5)

In [110]:
print(feature_matrix.shape)
print(type(feature_matrix))

(100, 5)
<class 'numpy.ndarray'>


In [111]:
X=pd.DataFrame(data=feature_matrix)

In [112]:
X.shape

(100, 5)

In [115]:
y=pd.DataFrame(data=label_vector)

In [116]:
y

0
0   202.490726
1    16.012209
2  -171.789420
3   -39.253232
4  -183.817971
..         ...
95   54.619736
96 -121.363479
97 -106.667974
98   59.556403
99    1.725254

[100 rows x 1 columns]

In [117]:
from sklearn.datasets import make_classification
?make_classification

In [127]:
X,y = make_classification(n_samples =100,n_features = 5,n_informative =3,n_classes =3,n_clusters_per_class=2)

In [133]:
X[:5]

array([[ 2.56159063, -2.1204778 , -1.04007077, -1.03335414,  1.49339563],
       [-0.71999893,  0.7669802 ,  0.7648656 , -0.73016575, -0.81574262],
       [-2.06347577, -1.66281996, -0.9712134 ,  0.42601497,  1.43187861],
       [-1.29520837, -1.97966419,  0.02272428, -2.94800703,  0.84859657],
       [ 1.73940547, -1.68997203, -0.59211962, -1.41090858,  1.03844843]])

In [138]:
X[:5,1:3]

array([[-2.1204778 , -1.04007077],
       [ 0.7669802 ,  0.7648656 ],
       [-1.66281996, -0.9712134 ],
       [-1.97966419,  0.02272428],
       [-1.68997203, -0.59211962]])